import { PrismaClient, CollegeType } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import bcrypt from "bcryptjs";
import { config } from "dotenv";

config({ path: ".env.local" });

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const colleges = [
  {
    name: "IIT Bombay",
    slug: "iit-bombay",
    location: "Mumbai, Maharashtra",
    city: "Mumbai", state: "Maharashtra",
    description: "One of India's premier engineering institutions, known for cutting-edge research and world-class faculty. Established in 1958, IIT Bombay consistently ranks among the top engineering colleges in Asia.",
    imageUrl: "https://picsum.photos/id/1040/800/500",
    totalFee: 200000, rating: 4.8, establishedYear: 1958, type: CollegeType.GOVERNMENT,
    affiliatedTo: "Autonomous (IIT)", placementPercent: 98.0, avgPackage: 2200000, highestPackage: 6500000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 200000, seats: 120 },
      { name: "B.Tech Electrical Engineering", duration: 4, fee: 200000, seats: 80 },
      { name: "M.Tech Data Science", duration: 2, fee: 50000, seats: 60 },
    ],
  },
  {
    name: "IIT Delhi",
    slug: "iit-delhi",
    location: "New Delhi, Delhi",
    city: "New Delhi", state: "Delhi",
    description: "Established in 1961, IIT Delhi is a leading technical university renowned for its rigorous academic programs, distinguished alumni, and strong industry ties in the capital region.",
    imageUrl: "https://picsum.photos/id/1060/800/500",
    totalFee: 210000, rating: 4.7, establishedYear: 1961, type: CollegeType.GOVERNMENT,
    affiliatedTo: "Autonomous (IIT)", placementPercent: 97.5, avgPackage: 2000000, highestPackage: 6000000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 210000, seats: 100 },
      { name: "B.Tech Mechanical Engineering", duration: 4, fee: 210000, seats: 90 },
      { name: "M.Tech AI & ML", duration: 2, fee: 60000, seats: 50 },
    ],
  },
  {
    name: "IIT Madras",
    slug: "iit-madras",
    location: "Chennai, Tamil Nadu",
    city: "Chennai", state: "Tamil Nadu",
    description: "IIT Madras is consistently ranked India's #1 engineering institution. It is known for research excellence, startup culture, and a scenic campus within a protected forest reserve.",
    imageUrl: "https://picsum.photos/id/1088/800/500",
    totalFee: 195000, rating: 4.9, establishedYear: 1959, type: CollegeType.GOVERNMENT,
    affiliatedTo: "Autonomous (IIT)", placementPercent: 98.5, avgPackage: 2400000, highestPackage: 7000000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 195000, seats: 110 },
      { name: "B.Tech Aerospace Engineering", duration: 4, fee: 195000, seats: 60 },
      { name: "M.Tech Robotics", duration: 2, fee: 55000, seats: 40 },
    ],
  },
  {
    name: "IIT Kanpur",
    slug: "iit-kanpur",
    location: "Kanpur, Uttar Pradesh",
    city: "Kanpur", state: "Uttar Pradesh",
    description: "IIT Kanpur is known for pioneering computer science education in India and for its strong research output across engineering and science disciplines.",
    imageUrl: "https://picsum.photos/id/1089/800/500",
    totalFee: 205000, rating: 4.7, establishedYear: 1959, type: CollegeType.GOVERNMENT,
    affiliatedTo: "Autonomous (IIT)", placementPercent: 96.0, avgPackage: 1950000, highestPackage: 6200000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 205000, seats: 100 },
      { name: "B.Tech Chemical Engineering", duration: 4, fee: 205000, seats: 80 },
      { name: "M.Tech Cybersecurity", duration: 2, fee: 55000, seats: 35 },
    ],
  },
  {
    name: "IIT Kharagpur",
    slug: "iit-kharagpur",
    location: "Kharagpur, West Bengal",
    city: "Kharagpur", state: "West Bengal",
    description: "The oldest and largest IIT, IIT Kharagpur has a sprawling 2100-acre campus and offers over 100 academic programs across engineering, sciences, law, and management.",
    imageUrl: "https://picsum.photos/id/1090/800/500",
    totalFee: 198000, rating: 4.6, establishedYear: 1951, type: CollegeType.GOVERNMENT,
    affiliatedTo: "Autonomous (IIT)", placementPercent: 95.5, avgPackage: 1850000, highestPackage: 6000000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 198000, seats: 130 },
      { name: "B.Tech Mining Engineering", duration: 4, fee: 198000, seats: 60 },
      { name: "MBA", duration: 2, fee: 280000, seats: 120 },
    ],
  },
  {
    name: "BITS Pilani",
    slug: "bits-pilani",
    location: "Pilani, Rajasthan",
    city: "Pilani", state: "Rajasthan",
    description: "BITS Pilani is a deemed university offering flexible dual-degree programs. Its practice school internship model and strong alumni network make it a top choice for engineering aspirants.",
    imageUrl: "https://picsum.photos/id/1073/800/500",
    totalFee: 450000, rating: 4.6, establishedYear: 1964, type: CollegeType.DEEMED,
    affiliatedTo: "BITS Pilani (Deemed University)", placementPercent: 95.0, avgPackage: 1800000, highestPackage: 5500000,
    courses: [
      { name: "B.E. Computer Science", duration: 4, fee: 450000, seats: 200 },
      { name: "B.E. Electronics", duration: 4, fee: 450000, seats: 150 },
      { name: "M.Sc. Mathematics", duration: 5, fee: 400000, seats: 60 },
    ],
  },
  {
    name: "NIT Trichy",
    slug: "nit-trichy",
    location: "Tiruchirappalli, Tamil Nadu",
    city: "Tiruchirappalli", state: "Tamil Nadu",
    description: "NIT Trichy consistently ranks among the top NITs in India. It is known for excellent infrastructure, quality faculty, and strong placement records in core engineering sectors.",
    imageUrl: "https://picsum.photos/id/1082/800/500",
    totalFee: 150000, rating: 4.4, establishedYear: 1964, type: CollegeType.GOVERNMENT,
    affiliatedTo: "Autonomous (NIT)", placementPercent: 92.0, avgPackage: 1200000, highestPackage: 4500000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 150000, seats: 120 },
      { name: "B.Tech Civil Engineering", duration: 4, fee: 130000, seats: 80 },
      { name: "M.Tech VLSI", duration: 2, fee: 40000, seats: 40 },
    ],
  },
  {
    name: "NIT Warangal",
    slug: "nit-warangal",
    location: "Warangal, Telangana",
    city: "Warangal", state: "Telangana",
    description: "NIT Warangal is one of the oldest and most prestigious NITs, known for strong alumni networks in the IT sector and excellent placements in top MNCs.",
    imageUrl: "https://picsum.photos/id/1091/800/500",
    totalFee: 145000, rating: 4.3, establishedYear: 1959, type: CollegeType.GOVERNMENT,
    affiliatedTo: "Autonomous (NIT)", placementPercent: 90.0, avgPackage: 1100000, highestPackage: 4200000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 145000, seats: 120 },
      { name: "B.Tech Electronics", duration: 4, fee: 145000, seats: 100 },
      { name: "B.Tech Metallurgical Engineering", duration: 4, fee: 130000, seats: 60 },
    ],
  },
  {
    name: "NIT Surathkal",
    slug: "nit-surathkal",
    location: "Mangalore, Karnataka",
    city: "Mangalore", state: "Karnataka",
    description: "NIT Karnataka (Surathkal) is set on a scenic coastal campus. It has a strong reputation in electronics, computer science, and chemical engineering with excellent industry linkages.",
    imageUrl: "https://picsum.photos/id/1092/800/500",
    totalFee: 148000, rating: 4.2, establishedYear: 1960, type: CollegeType.GOVERNMENT,
    affiliatedTo: "Autonomous (NIT)", placementPercent: 88.0, avgPackage: 1050000, highestPackage: 4000000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 148000, seats: 110 },
      { name: "B.Tech Chemical Engineering", duration: 4, fee: 140000, seats: 80 },
      { name: "M.Tech Structural Engineering", duration: 2, fee: 38000, seats: 30 },
    ],
  },
  {
    name: "VIT Vellore",
    slug: "vit-vellore",
    location: "Vellore, Tamil Nadu",
    city: "Vellore", state: "Tamil Nadu",
    description: "VIT Vellore is a private deemed university known for its industry-oriented curriculum, international collaborations, and one of India's largest placement drives attracting 600+ companies annually.",
    imageUrl: "https://picsum.photos/id/1080/800/500",
    totalFee: 185000, rating: 4.2, establishedYear: 1984, type: CollegeType.DEEMED,
    affiliatedTo: "VIT (Deemed University)", placementPercent: 88.0, avgPackage: 900000, highestPackage: 4000000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 185000, seats: 600 },
      { name: "B.Tech Mechanical Engineering", duration: 4, fee: 185000, seats: 300 },
      { name: "MBA", duration: 2, fee: 250000, seats: 120 },
    ],
  },
  {
    name: "Manipal Institute of Technology",
    slug: "manipal-institute-of-technology",
    location: "Manipal, Karnataka",
    city: "Manipal", state: "Karnataka",
    description: "MIT Manipal is a constituent institution of Manipal Academy of Higher Education. It is recognized for its diverse student community, modern labs, and strong global alumni presence.",
    imageUrl: "https://picsum.photos/id/1083/800/500",
    totalFee: 280000, rating: 4.1, establishedYear: 1957, type: CollegeType.PRIVATE,
    affiliatedTo: "Manipal Academy of Higher Education", placementPercent: 85.0, avgPackage: 800000, highestPackage: 3500000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 280000, seats: 300 },
      { name: "B.Tech Mechatronics", duration: 4, fee: 270000, seats: 100 },
      { name: "B.Tech Biomedical Engineering", duration: 4, fee: 250000, seats: 80 },
    ],
  },
  {
    name: "SRM Institute of Science and Technology",
    slug: "srm-institute",
    location: "Chennai, Tamil Nadu",
    city: "Chennai", state: "Tamil Nadu",
    description: "SRM Institute is one of India's largest private universities, offering a wide range of programs with strong industry connections, modern infrastructure, and active research centers.",
    imageUrl: "https://picsum.photos/id/1084/800/500",
    totalFee: 180000, rating: 3.9, establishedYear: 1985, type: CollegeType.PRIVATE,
    affiliatedTo: "SRM Institute (Deemed University)", placementPercent: 80.0, avgPackage: 650000, highestPackage: 3000000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 180000, seats: 800 },
      { name: "B.Tech Electronics", duration: 4, fee: 165000, seats: 400 },
      { name: "BCA", duration: 3, fee: 100000, seats: 200 },
    ],
  },
  {
    name: "Jadavpur University",
    slug: "jadavpur-university",
    location: "Kolkata, West Bengal",
    city: "Kolkata", state: "West Bengal",
    description: "Jadavpur University is one of Eastern India's most reputed public universities, known for producing top engineers, scientists, and academics at very low cost.",
    imageUrl: "https://picsum.photos/id/1085/800/500",
    totalFee: 50000, rating: 4.3, establishedYear: 1955, type: CollegeType.GOVERNMENT,
    affiliatedTo: "Autonomous (State University)", placementPercent: 87.0, avgPackage: 950000, highestPackage: 4000000,
    courses: [
      { name: "B.E. Computer Science", duration: 4, fee: 50000, seats: 90 },
      { name: "B.E. Electrical Engineering", duration: 4, fee: 50000, seats: 90 },
      { name: "M.E. Software Engineering", duration: 2, fee: 30000, seats: 30 },
    ],
  },
  {
    name: "Amity University Noida",
    slug: "amity-university-noida",
    location: "Noida, Uttar Pradesh",
    city: "Noida", state: "Uttar Pradesh",
    description: "Amity University is one of India's largest private universities with a sprawling campus, global collaborations, and a wide range of programs spanning engineering, management, and law.",
    imageUrl: "https://picsum.photos/id/1086/800/500",
    totalFee: 220000, rating: 3.7, establishedYear: 2005, type: CollegeType.PRIVATE,
    affiliatedTo: "Amity University (Private)", placementPercent: 75.0, avgPackage: 550000, highestPackage: 2500000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 220000, seats: 400 },
      { name: "BBA", duration: 3, fee: 180000, seats: 300 },
      { name: "MBA", duration: 2, fee: 300000, seats: 200 },
    ],
  },
  {
    name: "PSG College of Technology",
    slug: "psg-college-of-technology",
    location: "Coimbatore, Tamil Nadu",
    city: "Coimbatore", state: "Tamil Nadu",
    description: "PSG College of Technology is an autonomous institution with NAAC A++ accreditation, consistently ranked among the top private engineering colleges in Tamil Nadu.",
    imageUrl: "https://picsum.photos/id/1087/800/500",
    totalFee: 95000, rating: 4.0, establishedYear: 1951, type: CollegeType.AUTONOMOUS,
    affiliatedTo: "Anna University", placementPercent: 83.0, avgPackage: 700000, highestPackage: 3200000,
    courses: [
      { name: "B.E. Computer Science", duration: 4, fee: 95000, seats: 120 },
      { name: "B.E. Mechanical Engineering", duration: 4, fee: 85000, seats: 120 },
      { name: "B.Tech Information Technology", duration: 4, fee: 90000, seats: 90 },
    ],
  },
  {
    name: "Delhi Technological University",
    slug: "delhi-technological-university",
    location: "New Delhi, Delhi",
    city: "New Delhi", state: "Delhi",
    description: "DTU, formerly Delhi College of Engineering, is one of Delhi's top state engineering universities. It is known for strong placements in product companies and a vibrant startup culture.",
    imageUrl: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800",
    totalFee: 165000, rating: 4.1, establishedYear: 1941, type: CollegeType.GOVERNMENT,
    affiliatedTo: "Autonomous (State University)", placementPercent: 88.0, avgPackage: 1000000, highestPackage: 4500000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 165000, seats: 180 },
      { name: "B.Tech Software Engineering", duration: 4, fee: 165000, seats: 120 },
      { name: "M.Tech Machine Learning", duration: 2, fee: 50000, seats: 40 },
    ],
  },
  {
    name: "IIIT Hyderabad",
    slug: "iiit-hyderabad",
    location: "Hyderabad, Telangana",
    city: "Hyderabad", state: "Telangana",
    description: "IIIT Hyderabad is an autonomous research university focused on computer science and IT. It is renowned for its research-driven curriculum and strong ties with the Hyderabad tech ecosystem.",
    imageUrl: "https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=800",
    totalFee: 320000, rating: 4.5, establishedYear: 1998, type: CollegeType.AUTONOMOUS,
    affiliatedTo: "Autonomous (IIIT)", placementPercent: 96.0, avgPackage: 1700000, highestPackage: 5800000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 320000, seats: 120 },
      { name: "B.Tech Electronics & Communication", duration: 4, fee: 320000, seats: 80 },
      { name: "M.Tech Computational Linguistics", duration: 2, fee: 120000, seats: 30 },
    ],
  },
  {
    name: "Thapar Institute of Engineering",
    slug: "thapar-institute",
    location: "Patiala, Punjab",
    city: "Patiala", state: "Punjab",
    description: "Thapar Institute is a deemed university with a strong focus on engineering and technology. It has excellent industry connections and a high placement rate in IT companies.",
    imageUrl: "https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=800",
    totalFee: 310000, rating: 4.0, establishedYear: 1956, type: CollegeType.DEEMED,
    affiliatedTo: "Thapar Institute (Deemed University)", placementPercent: 86.0, avgPackage: 850000, highestPackage: 3800000,
    courses: [
      { name: "B.E. Computer Science", duration: 4, fee: 310000, seats: 200 },
      { name: "B.E. Electronics", duration: 4, fee: 310000, seats: 150 },
      { name: "B.E. Civil Engineering", duration: 4, fee: 290000, seats: 100 },
    ],
  },
  {
    name: "COEP Technological University",
    slug: "coep-technological-university",
    location: "Pune, Maharashtra",
    city: "Pune", state: "Maharashtra",
    description: "COEP is one of the oldest engineering colleges in Asia, established in 1854. It is a premier autonomous institution under the University of Pune with a proud legacy and strong alumni.",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
    totalFee: 120000, rating: 4.1, establishedYear: 1854, type: CollegeType.AUTONOMOUS,
    affiliatedTo: "Savitribai Phule Pune University", placementPercent: 84.0, avgPackage: 780000, highestPackage: 3500000,
    courses: [
      { name: "B.Tech Computer Engineering", duration: 4, fee: 120000, seats: 120 },
      { name: "B.Tech Mechanical Engineering", duration: 4, fee: 110000, seats: 120 },
      { name: "B.Tech Electronics", duration: 4, fee: 115000, seats: 90 },
    ],
  },
  {
    name: "Pune Institute of Computer Technology",
    slug: "pict-pune",
    location: "Pune, Maharashtra",
    city: "Pune", state: "Maharashtra",
    description: "PICT is a leading autonomous engineering college in Pune, known for its strong focus on computer science, consistent top placements, and a highly active technical community.",
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800",
    totalFee: 110000, rating: 3.9, establishedYear: 1983, type: CollegeType.AUTONOMOUS,
    affiliatedTo: "Savitribai Phule Pune University", placementPercent: 82.0, avgPackage: 720000, highestPackage: 3000000,
    courses: [
      { name: "B.E. Computer Engineering", duration: 4, fee: 110000, seats: 240 },
      { name: "B.E. Information Technology", duration: 4, fee: 110000, seats: 120 },
      { name: "M.E. Computer Engineering", duration: 2, fee: 80000, seats: 24 },
    ],
  },
  {
    name: "BMS College of Engineering",
    slug: "bms-college-of-engineering",
    location: "Bengaluru, Karnataka",
    city: "Bengaluru", state: "Karnataka",
    description: "BMS College of Engineering is one of Bengaluru's oldest and most reputed engineering colleges, affiliated to VTU and known for strong industry connections in the Silicon Valley of India.",
    imageUrl: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800",
    totalFee: 130000, rating: 3.9, establishedYear: 1946, type: CollegeType.AUTONOMOUS,
    affiliatedTo: "Visvesvaraya Technological University", placementPercent: 81.0, avgPackage: 700000, highestPackage: 3200000,
    courses: [
      { name: "B.E. Computer Science", duration: 4, fee: 130000, seats: 180 },
      { name: "B.E. Electronics", duration: 4, fee: 125000, seats: 120 },
      { name: "B.E. Mechanical Engineering", duration: 4, fee: 120000, seats: 120 },
    ],
  },
  {
    name: "RV College of Engineering",
    slug: "rv-college-of-engineering",
    location: "Bengaluru, Karnataka",
    city: "Bengaluru", state: "Karnataka",
    description: "RVCE is one of Karnataka's top private engineering colleges, consistently producing top-ranked IT professionals and entrepreneurs with a focus on industry-ready education.",
    imageUrl: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800",
    totalFee: 135000, rating: 4.0, establishedYear: 1963, type: CollegeType.AUTONOMOUS,
    affiliatedTo: "Visvesvaraya Technological University", placementPercent: 83.0, avgPackage: 740000, highestPackage: 3400000,
    courses: [
      { name: "B.E. Computer Science", duration: 4, fee: 135000, seats: 180 },
      { name: "B.E. Information Science", duration: 4, fee: 130000, seats: 120 },
      { name: "B.E. Civil Engineering", duration: 4, fee: 120000, seats: 90 },
    ],
  },
  {
    name: "PES University",
    slug: "pes-university",
    location: "Bengaluru, Karnataka",
    city: "Bengaluru", state: "Karnataka",
    description: "PES University is a prominent private university in Bengaluru known for its computer science and engineering programs, strong tech alumni, and close ties to the Bengaluru startup ecosystem.",
    imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800",
    totalFee: 195000, rating: 4.0, establishedYear: 1972, type: CollegeType.PRIVATE,
    affiliatedTo: "PES University (Private)", placementPercent: 84.0, avgPackage: 760000, highestPackage: 3500000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 195000, seats: 240 },
      { name: "B.Tech Electronics", duration: 4, fee: 185000, seats: 120 },
      { name: "MBA", duration: 2, fee: 250000, seats: 60 },
    ],
  },
  {
    name: "Vellore Institute of Technology Chennai",
    slug: "vit-chennai",
    location: "Chennai, Tamil Nadu",
    city: "Chennai", state: "Tamil Nadu",
    description: "VIT Chennai is a campus of VIT University that benefits from its proximity to Chennai's IT corridor, offering strong placement opportunities in top tech companies.",
    imageUrl: "https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=800",
    totalFee: 190000, rating: 4.0, establishedYear: 2010, type: CollegeType.DEEMED,
    affiliatedTo: "VIT (Deemed University)", placementPercent: 85.0, avgPackage: 850000, highestPackage: 3800000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 190000, seats: 360 },
      { name: "B.Tech AI & Data Science", duration: 4, fee: 200000, seats: 180 },
      { name: "B.Tech Civil Engineering", duration: 4, fee: 175000, seats: 120 },
    ],
  },
  {
    name: "Symbiosis Institute of Technology",
    slug: "symbiosis-institute-of-technology",
    location: "Pune, Maharashtra",
    city: "Pune", state: "Maharashtra",
    description: "SIT Pune is a part of Symbiosis International University, offering industry-aligned engineering programs with a strong focus on innovation, entrepreneurship, and global exposure.",
    imageUrl: "https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=800",
    totalFee: 270000, rating: 3.8, establishedYear: 2008, type: CollegeType.DEEMED,
    affiliatedTo: "Symbiosis International University", placementPercent: 79.0, avgPackage: 630000, highestPackage: 2800000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 270000, seats: 180 },
      { name: "B.Tech Mechanical Engineering", duration: 4, fee: 260000, seats: 90 },
      { name: "M.Tech Design Engineering", duration: 2, fee: 180000, seats: 30 },
    ],
  },
  {
    name: "Birla Institute of Technology Mesra",
    slug: "bit-mesra",
    location: "Ranchi, Jharkhand",
    city: "Ranchi", state: "Jharkhand",
    description: "BIT Mesra is one of India's well-known private technical universities offering a wide range of programs. It has a scenic campus and strong alumni networks across industries.",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
    totalFee: 240000, rating: 3.8, establishedYear: 1955, type: CollegeType.DEEMED,
    affiliatedTo: "BIT Mesra (Deemed University)", placementPercent: 76.0, avgPackage: 580000, highestPackage: 2600000,
    courses: [
      { name: "B.E. Computer Science", duration: 4, fee: 240000, seats: 120 },
      { name: "B.E. Electronics", duration: 4, fee: 235000, seats: 90 },
      { name: "B.E. Biotechnology", duration: 4, fee: 225000, seats: 60 },
    ],
  },
  {
    name: "Kalinga Institute of Industrial Technology",
    slug: "kiit-bhubaneswar",
    location: "Bhubaneswar, Odisha",
    city: "Bhubaneswar", state: "Odisha",
    description: "KIIT Bhubaneswar is a deemed university with one of the fastest-growing campuses in India. It is known for its large student intake, modern facilities, and strong corporate partnerships.",
    imageUrl: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800",
    totalFee: 260000, rating: 3.8, establishedYear: 1992, type: CollegeType.DEEMED,
    affiliatedTo: "KIIT (Deemed University)", placementPercent: 78.0, avgPackage: 600000, highestPackage: 2800000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 260000, seats: 600 },
      { name: "B.Tech Electrical Engineering", duration: 4, fee: 250000, seats: 300 },
      { name: "MBA", duration: 2, fee: 350000, seats: 180 },
    ],
  },
  {
    name: "LNM Institute of Information Technology",
    slug: "lnmiit-jaipur",
    location: "Jaipur, Rajasthan",
    city: "Jaipur", state: "Rajasthan",
    description: "LNMIIT is a private university dedicated to IT and computer science. Located in Jaipur, it has strong placements in product-based tech companies and a vibrant coding culture.",
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800",
    totalFee: 220000, rating: 3.9, establishedYear: 2002, type: CollegeType.PRIVATE,
    affiliatedTo: "LNMIIT (Private University)", placementPercent: 81.0, avgPackage: 750000, highestPackage: 3200000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 220000, seats: 180 },
      { name: "B.Tech Electronics", duration: 4, fee: 215000, seats: 90 },
      { name: "M.Tech Computer Science", duration: 2, fee: 100000, seats: 30 },
    ],
  },
  {
    name: "Shiv Nadar University",
    slug: "shiv-nadar-university",
    location: "Greater Noida, Uttar Pradesh",
    city: "Greater Noida", state: "Uttar Pradesh",
    description: "Shiv Nadar University is a research-focused private university with a liberal arts approach to engineering education, a world-class campus, and strong industry connections.",
    imageUrl: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800",
    totalFee: 350000, rating: 4.1, establishedYear: 2011, type: CollegeType.PRIVATE,
    affiliatedTo: "Shiv Nadar University (Private)", placementPercent: 87.0, avgPackage: 900000, highestPackage: 4000000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 350000, seats: 200 },
      { name: "B.Tech Electrical Engineering", duration: 4, fee: 340000, seats: 100 },
      { name: "B.Sc. Physics", duration: 3, fee: 300000, seats: 60 },
    ],
  },
  {
    name: "Chandigarh University",
    slug: "chandigarh-university",
    location: "Chandigarh, Punjab",
    city: "Chandigarh", state: "Punjab",
    description: "Chandigarh University is one of North India's largest private universities, known for its huge placement drive, diverse student community, and strong industry tie-ups.",
    imageUrl: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800",
    totalFee: 165000, rating: 3.7, establishedYear: 2012, type: CollegeType.PRIVATE,
    affiliatedTo: "Chandigarh University (Private)", placementPercent: 74.0, avgPackage: 520000, highestPackage: 2400000,
    courses: [
      { name: "B.E. Computer Science", duration: 4, fee: 165000, seats: 800 },
      { name: "B.E. Mechanical Engineering", duration: 4, fee: 155000, seats: 400 },
      { name: "MBA", duration: 2, fee: 220000, seats: 300 },
    ],
  },
  {
    name: "Lovely Professional University",
    slug: "lovely-professional-university",
    location: "Phagwara, Punjab",
    city: "Phagwara", state: "Punjab",
    description: "LPU is one of India's largest single-campus universities offering 200+ programs. It is known for its diverse student intake from across India and multiple international collaborations.",
    imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800",
    totalFee: 140000, rating: 3.6, establishedYear: 2005, type: CollegeType.PRIVATE,
    affiliatedTo: "Lovely Professional University (Private)", placementPercent: 70.0, avgPackage: 450000, highestPackage: 2000000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 140000, seats: 1200 },
      { name: "BBA", duration: 3, fee: 120000, seats: 600 },
      { name: "B.Tech Mechanical Engineering", duration: 4, fee: 130000, seats: 400 },
    ],
  },
  {
    name: "Vit-AP University",
    slug: "vit-ap-university",
    location: "Amaravati, Andhra Pradesh",
    city: "Amaravati", state: "Andhra Pradesh",
    description: "VIT-AP is a newly established campus of VIT University in the new capital region of Andhra Pradesh, rapidly growing with modern infrastructure and strong placements.",
    imageUrl: "https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=800",
    totalFee: 175000, rating: 3.8, establishedYear: 2017, type: CollegeType.DEEMED,
    affiliatedTo: "VIT (Deemed University)", placementPercent: 77.0, avgPackage: 600000, highestPackage: 2600000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 175000, seats: 300 },
      { name: "B.Tech AI & Machine Learning", duration: 4, fee: 185000, seats: 120 },
      { name: "B.Tech Civil Engineering", duration: 4, fee: 160000, seats: 90 },
    ],
  },
  {
    name: "Anna University",
    slug: "anna-university",
    location: "Chennai, Tamil Nadu",
    city: "Chennai", state: "Tamil Nadu",
    description: "Anna University is a premier state technical university in Tamil Nadu that also governs hundreds of affiliated engineering colleges. Its flagship campus is well-known for research excellence.",
    imageUrl: "https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=800",
    totalFee: 75000, rating: 4.2, establishedYear: 1978, type: CollegeType.GOVERNMENT,
    affiliatedTo: "Autonomous (State University)", placementPercent: 85.0, avgPackage: 800000, highestPackage: 3500000,
    courses: [
      { name: "B.E. Computer Science", duration: 4, fee: 75000, seats: 120 },
      { name: "B.E. Information Technology", duration: 4, fee: 70000, seats: 90 },
      { name: "M.E. Applied Electronics", duration: 2, fee: 40000, seats: 30 },
    ],
  },
  {
    name: "Osmania University",
    slug: "osmania-university",
    location: "Hyderabad, Telangana",
    city: "Hyderabad", state: "Telangana",
    description: "Osmania University is one of the oldest universities in India with a rich heritage campus and a large network of affiliated colleges across Telangana.",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
    totalFee: 60000, rating: 3.8, establishedYear: 1918, type: CollegeType.GOVERNMENT,
    affiliatedTo: "Autonomous (State University)", placementPercent: 72.0, avgPackage: 480000, highestPackage: 2000000,
    courses: [
      { name: "B.E. Computer Science", duration: 4, fee: 60000, seats: 120 },
      { name: "B.Sc. Physics", duration: 3, fee: 30000, seats: 90 },
      { name: "MBA", duration: 2, fee: 80000, seats: 60 },
    ],
  },
  {
    name: "Savitribai Phule Pune University",
    slug: "sppu-pune",
    location: "Pune, Maharashtra",
    city: "Pune", state: "Maharashtra",
    description: "One of the oldest and largest universities in Maharashtra, SPPU is known for its extensive academic programs, research centres, and affiliation to 800+ colleges across Pune and surrounding districts.",
    imageUrl: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800",
    totalFee: 55000, rating: 3.9, establishedYear: 1948, type: CollegeType.GOVERNMENT,
    affiliatedTo: "Autonomous (State University)", placementPercent: 74.0, avgPackage: 500000, highestPackage: 2200000,
    courses: [
      { name: "B.E. Computer Engineering", duration: 4, fee: 55000, seats: 180 },
      { name: "B.Sc. Computer Science", duration: 3, fee: 30000, seats: 120 },
      { name: "MBA", duration: 2, fee: 90000, seats: 90 },
    ],
  },
  {
    name: "Ramaiah Institute of Technology",
    slug: "ramaiah-institute-of-technology",
    location: "Bengaluru, Karnataka",
    city: "Bengaluru", state: "Karnataka",
    description: "Ramaiah Institute of Technology is one of Bengaluru's well-established engineering colleges with strong placements across IT and manufacturing sectors and a large alumni network.",
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800",
    totalFee: 128000, rating: 3.9, establishedYear: 1962, type: CollegeType.AUTONOMOUS,
    affiliatedTo: "Visvesvaraya Technological University", placementPercent: 80.0, avgPackage: 680000, highestPackage: 2900000,
    courses: [
      { name: "B.E. Computer Science", duration: 4, fee: 128000, seats: 180 },
      { name: "B.E. Electronics", duration: 4, fee: 122000, seats: 120 },
      { name: "B.E. Civil Engineering", duration: 4, fee: 115000, seats: 90 },
    ],
  },
  {
    name: "Netaji Subhas University of Technology",
    slug: "nsut-delhi",
    location: "New Delhi, Delhi",
    city: "New Delhi", state: "Delhi",
    description: "NSUT (formerly NSIT) is one of Delhi's top state engineering universities, consistently producing high-quality software engineers placed in top product and service companies.",
    imageUrl: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800",
    totalFee: 162000, rating: 4.0, establishedYear: 1983, type: CollegeType.GOVERNMENT,
    affiliatedTo: "Autonomous (State University)", placementPercent: 86.0, avgPackage: 950000, highestPackage: 4200000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 162000, seats: 120 },
      { name: "B.Tech Electronics", duration: 4, fee: 160000, seats: 90 },
      { name: "B.Tech Information Technology", duration: 4, fee: 160000, seats: 90 },
    ],
  },
  {
    name: "Indraprastha Institute of Information Technology",
    slug: "iiit-delhi",
    location: "New Delhi, Delhi",
    city: "New Delhi", state: "Delhi",
    description: "IIIT Delhi is a research-intensive state university focused on IT and interdisciplinary programs. It has a rigorous curriculum and consistently strong placements in product-based companies.",
    imageUrl: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800",
    totalFee: 280000, rating: 4.3, establishedYear: 2008, type: CollegeType.GOVERNMENT,
    affiliatedTo: "Autonomous (State University)", placementPercent: 93.0, avgPackage: 1500000, highestPackage: 5500000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 280000, seats: 120 },
      { name: "B.Tech Electronics & Communication", duration: 4, fee: 280000, seats: 60 },
      { name: "M.Tech Artificial Intelligence", duration: 2, fee: 110000, seats: 30 },
    ],
  },
  {
    name: "Nirma University",
    slug: "nirma-university",
    location: "Ahmedabad, Gujarat",
    city: "Ahmedabad", state: "Gujarat",
    description: "Nirma University is one of Gujarat's top private universities, offering programs in engineering, management, law, and pharmacy with strong industry linkages in Ahmedabad's industrial belt.",
    imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800",
    totalFee: 175000, rating: 3.9, establishedYear: 1994, type: CollegeType.PRIVATE,
    affiliatedTo: "Nirma University (Private)", placementPercent: 80.0, avgPackage: 660000, highestPackage: 3000000,
    courses: [
      { name: "B.Tech Computer Engineering", duration: 4, fee: 175000, seats: 180 },
      { name: "B.Tech Chemical Engineering", duration: 4, fee: 165000, seats: 90 },
      { name: "MBA", duration: 2, fee: 280000, seats: 120 },
    ],
  },
  {
    name: "Dhirubhai Ambani Institute of ICT",
    slug: "da-iict",
    location: "Gandhinagar, Gujarat",
    city: "Gandhinagar", state: "Gujarat",
    description: "DA-IICT is a premier private technical university in Gujarat dedicated to ICT education. It is known for outstanding placements in top tech companies and a focused, research-oriented curriculum.",
    imageUrl: "https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=800",
    totalFee: 290000, rating: 4.2, establishedYear: 2001, type: CollegeType.PRIVATE,
    affiliatedTo: "DA-IICT (Private University)", placementPercent: 91.0, avgPackage: 1100000, highestPackage: 4500000,
    courses: [
      { name: "B.Tech ICT", duration: 4, fee: 290000, seats: 180 },
      { name: "B.Tech ICT with CS", duration: 4, fee: 300000, seats: 90 },
      { name: "M.Tech ICT", duration: 2, fee: 130000, seats: 30 },
    ],
  },
  {
    name: "Sardar Vallabhbhai National Institute of Technology",
    slug: "svnit-surat",
    location: "Surat, Gujarat",
    city: "Surat", state: "Gujarat",
    description: "SVNIT Surat is one of the prominent NITs, well-regarded for its engineering programs and placement record in core and IT sectors, benefiting from Surat's industrial ecosystem.",
    imageUrl: "https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=800",
    totalFee: 143000, rating: 4.1, establishedYear: 1961, type: CollegeType.GOVERNMENT,
    affiliatedTo: "Autonomous (NIT)", placementPercent: 87.0, avgPackage: 920000, highestPackage: 3900000,
    courses: [
      { name: "B.Tech Computer Engineering", duration: 4, fee: 143000, seats: 120 },
      { name: "B.Tech Chemical Engineering", duration: 4, fee: 135000, seats: 90 },
      { name: "B.Tech Civil Engineering", duration: 4, fee: 130000, seats: 90 },
    ],
  },
  {
    name: "Presidency University Bengaluru",
    slug: "presidency-university-bengaluru",
    location: "Bengaluru, Karnataka",
    city: "Bengaluru", state: "Karnataka",
    description: "Presidency University Bengaluru is a private university with a rapidly expanding campus and programs in engineering, management, and law, attracting students from across South India.",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
    totalFee: 155000, rating: 3.6, establishedYear: 2013, type: CollegeType.PRIVATE,
    affiliatedTo: "Presidency University (Private)", placementPercent: 68.0, avgPackage: 420000, highestPackage: 1800000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 155000, seats: 240 },
      { name: "BBA", duration: 3, fee: 130000, seats: 180 },
      { name: "MBA", duration: 2, fee: 200000, seats: 120 },
    ],
  },
  {
    name: "Jaypee Institute of Information Technology",
    slug: "jiit-noida",
    location: "Noida, Uttar Pradesh",
    city: "Noida", state: "Uttar Pradesh",
    description: "JIIT Noida is a private university with a strong focus on IT and computer science, well-positioned near Delhi's tech corridor with consistent placements in IT companies.",
    imageUrl: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800",
    totalFee: 210000, rating: 3.8, establishedYear: 2001, type: CollegeType.PRIVATE,
    affiliatedTo: "JIIT (Deemed University)", placementPercent: 78.0, avgPackage: 640000, highestPackage: 2700000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 210000, seats: 240 },
      { name: "B.Tech Electronics", duration: 4, fee: 205000, seats: 120 },
      { name: "M.Tech Computer Science", duration: 2, fee: 90000, seats: 30 },
    ],
  },
  {
    name: "Maulana Abul Kalam Azad University of Technology",
    slug: "makaut-bengal",
    location: "Kolkata, West Bengal",
    city: "Kolkata", state: "West Bengal",
    description: "MAKAUT is the premier technical university of West Bengal, governing over 150 engineering colleges. Its flagship programs are well-regarded in Eastern India's industrial sector.",
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800",
    totalFee: 65000, rating: 3.7, establishedYear: 2000, type: CollegeType.GOVERNMENT,
    affiliatedTo: "Autonomous (State University)", placementPercent: 70.0, avgPackage: 430000, highestPackage: 1800000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 65000, seats: 120 },
      { name: "B.Tech Electronics", duration: 4, fee: 62000, seats: 90 },
      { name: "B.Tech Civil Engineering", duration: 4, fee: 58000, seats: 60 },
    ],
  },
  {
    name: "Indian Institute of Engineering Science and Technology Shibpur",
    slug: "iiest-shibpur",
    location: "Howrah, West Bengal",
    city: "Howrah", state: "West Bengal",
    description: "IIEST Shibpur is one of India's oldest technical institutions, established in 1856. It is an Institute of National Importance known for civil and mechanical engineering excellence.",
    imageUrl: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800",
    totalFee: 130000, rating: 4.0, establishedYear: 1856, type: CollegeType.GOVERNMENT,
    affiliatedTo: "Autonomous (Institute of National Importance)", placementPercent: 82.0, avgPackage: 750000, highestPackage: 3300000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 130000, seats: 90 },
      { name: "B.Tech Civil Engineering", duration: 4, fee: 120000, seats: 120 },
      { name: "B.Tech Mechanical Engineering", duration: 4, fee: 120000, seats: 120 },
    ],
  },
  {
    name: "Koneru Lakshmaiah Education Foundation",
    slug: "klef-vijayawada",
    location: "Vijayawada, Andhra Pradesh",
    city: "Vijayawada", state: "Andhra Pradesh",
    description: "KL University is a deemed university in Andhra Pradesh known for its large campus, diverse engineering programs, and growing placement record particularly in IT and electronics.",
    imageUrl: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800",
    totalFee: 155000, rating: 3.7, establishedYear: 1980, type: CollegeType.DEEMED,
    affiliatedTo: "KL University (Deemed University)", placementPercent: 73.0, avgPackage: 490000, highestPackage: 2100000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 155000, seats: 500 },
      { name: "B.Tech Electronics", duration: 4, fee: 145000, seats: 250 },
      { name: "MBA", duration: 2, fee: 200000, seats: 120 },
    ],
  },
  {
    name: "SRM University Andhra Pradesh",
    slug: "srm-ap",
    location: "Amaravati, Andhra Pradesh",
    city: "Amaravati", state: "Andhra Pradesh",
    description: "SRM AP is a new campus of the SRM group in the planned capital city of Andhra Pradesh, offering modern facilities, global faculty, and strong foundational programs.",
    imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800",
    totalFee: 170000, rating: 3.7, establishedYear: 2017, type: CollegeType.PRIVATE,
    affiliatedTo: "SRM University AP (Private)", placementPercent: 72.0, avgPackage: 480000, highestPackage: 2000000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 170000, seats: 300 },
      { name: "B.Tech Electrical Engineering", duration: 4, fee: 160000, seats: 150 },
      { name: "B.Sc. Data Science", duration: 3, fee: 130000, seats: 90 },
    ],
  },
  {
    name: "Visvesvaraya National Institute of Technology Nagpur",
    slug: "vnit-nagpur",
    location: "Nagpur, Maharashtra",
    city: "Nagpur", state: "Maharashtra",
    description: "VNIT Nagpur is a premier NIT in central India known for its strong engineering programs and placement record, with special strengths in civil, mechanical, and computer engineering.",
    imageUrl: "https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=800",
    totalFee: 147000, rating: 4.2, establishedYear: 1960, type: CollegeType.GOVERNMENT,
    affiliatedTo: "Autonomous (NIT)", placementPercent: 89.0, avgPackage: 980000, highestPackage: 4100000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 147000, seats: 120 },
      { name: "B.Tech Civil Engineering", duration: 4, fee: 135000, seats: 90 },
      { name: "B.Tech Mechanical Engineering", duration: 4, fee: 138000, seats: 90 },
    ],
  },
  {
    name: "Medicaps University",
    slug: "medicaps-university",
    location: "Indore, Madhya Pradesh",
    city: "Indore", state: "Madhya Pradesh",
    description: "Medicaps University is a private university in Indore offering engineering, management, and commerce programs with a focus on skill development and employability.",
    imageUrl: "https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=800",
    totalFee: 120000, rating: 3.5, establishedYear: 2000, type: CollegeType.PRIVATE,
    affiliatedTo: "Medicaps University (Private)", placementPercent: 65.0, avgPackage: 380000, highestPackage: 1500000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 120000, seats: 180 },
      { name: "BBA", duration: 3, fee: 90000, seats: 120 },
      { name: "MBA", duration: 2, fee: 150000, seats: 90 },
    ],
  },
  {
    name: "SAGE University Indore",
    slug: "sage-university-indore",
    location: "Indore, Madhya Pradesh",
    city: "Indore", state: "Madhya Pradesh",
    description: "SAGE University is a growing private university in Indore with a broad range of programs and a focus on practical education, industry internships, and skill development.",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
    totalFee: 90000, rating: 3.4, establishedYear: 2017, type: CollegeType.PRIVATE,
    affiliatedTo: "SAGE University (Private)", placementPercent: 60.0, avgPackage: 320000, highestPackage: 1200000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 90000, seats: 240 },
      { name: "BCA", duration: 3, fee: 70000, seats: 180 },
      { name: "MBA", duration: 2, fee: 120000, seats: 90 },
    ],
  },
  {
    name: "IIT Roorkee",
    slug: "iit-roorkee",
    location: "Roorkee, Uttarakhand",
    city: "Roorkee", state: "Uttarakhand",
    description: "IIT Roorkee is the oldest technical institute in Asia, established in 1847. It is known for its civil and structural engineering heritage and strong modern research output.",
    imageUrl: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800",
    totalFee: 202000, rating: 4.6, establishedYear: 1847, type: CollegeType.GOVERNMENT,
    affiliatedTo: "Autonomous (IIT)", placementPercent: 94.0, avgPackage: 1750000, highestPackage: 5800000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 202000, seats: 100 },
      { name: "B.Tech Civil Engineering", duration: 4, fee: 202000, seats: 120 },
      { name: "M.Tech Earthquake Engineering", duration: 2, fee: 55000, seats: 30 },
    ],
  },
  {
    name: "IIT Guwahati",
    slug: "iit-guwahati",
    location: "Guwahati, Assam",
    city: "Guwahati", state: "Assam",
    description: "IIT Guwahati is the gateway IIT for the Northeast region, known for its scenic riverside campus and growing research profile in computer science, biosciences, and engineering.",
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800",
    totalFee: 198000, rating: 4.5, establishedYear: 1994, type: CollegeType.GOVERNMENT,
    affiliatedTo: "Autonomous (IIT)", placementPercent: 93.0, avgPackage: 1650000, highestPackage: 5500000,
    courses: [
      { name: "B.Tech Computer Science", duration: 4, fee: 198000, seats: 90 },
      { name: "B.Tech Bioscience & Bioengineering", duration: 4, fee: 198000, seats: 40 },
      { name: "M.Tech Data Analytics", duration: 2, fee: 50000, seats: 25 },
    ],
  },
];

async function main() {
  console.log("🌱 Seeding database...");

  const hashedPassword = await bcrypt.hash("password123", 10);
  await prisma.user.upsert({
    where: { email: "demo@example.com" },
    update: {},
    create: { name: "Demo User", email: "demo@example.com", password: hashedPassword },
  });
  console.log("✅ Demo user: demo@example.com / password123");

  for (const college of colleges) {
    const { courses, ...collegeData } = college;
    const created = await prisma.college.upsert({
      where: { slug: college.slug },
      update: {},
      create: { ...collegeData, courses: { create: courses } },
    });
    console.log(`✅ Seeded: ${created.name}`);
  }

  console.log(`\n🎉 Seeding complete! ${colleges.length} colleges seeded.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
